### ISSUE TITLE
wl module does not build on fedora 31 x86-64 kernel 5.6

### ISSUE THREAD

**Issue by dmitry-sensei** [UnitedRPMs/broadcom-wl-dkms#4]
Wl module did not build on fedora 31 x86-64 kernel 5.6.x.

**Comment by kuboosoft** [comment]
@dmitry-sensei In theory, the new update should resolve it. Thanks for the report.

`dnf clean all && dnf -y update`

**Comment by dmitry-sensei** [comment]
Ok. I'll try it

**Comment by dmitry-sensei** [comment]
Good. The module was built. But Network Manager does not see any wifi hotspots.
Инночка :*, [02.05.2020, 19:00]
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5685] dhcp4 (enp0s20u1): state changed unknown -> bound
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5552] dhcp4 (enp0s20u1): activation: beginning transaction (timeout in 45 seconds)
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5546] device (enp0s20u1): state change: config -> ip-config (reason 'none', sys-iface-state: 'assume')
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5520] agent-manager: req[0x55d186445e00, :1.177/org.freedesktop.nm-applet/1001]: agent registered
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: wlp8s0: CTRL-EVENT-SCAN-FAILED ret=-1
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: ioctl[SIOCSIWSCAN]: Invalid argument
мая 02 18:57:58 dmitriy-Inspiron-3721.lan kernel: WLC_SCAN error (-22)
мая 02 18:57:58 dmitriy-Inspiron-3721.lan kernel: ERROR @wl_cfg80211_scan : 
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5415] device (wlp8s0): state change: unavailable -> disconnected (reason 'supplicant-available', sys-iface-state:>
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5413] device (wlp8s0): supplicant interface state: starting -> ready
мая 02 18:57:58 dmitriy-Inspiron-3721.lan systemd[3031]: Started dbus-:1.2-org.freedesktop.Notifications@2.service.
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5368] sup-iface[0x55d1863b1910,wlp8s0]: supports 1 scan SSIDs
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: dbus: fill_dict_with_properties dbus_interface=fi.w1.wpa_supplicant1.Interface.P2PDevice dbus_property=P2PDeviceConfig getter failed
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: ioctl[SIOCSIWENCODEEXT]: Invalid argument
мая 02 18:58:28 dmitriy-Inspiron-3721.lan audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib>
мая 02 18:58:28 dmitriy-Inspiron-3721.lan systemd[1]: systemd-hostnamed.service: Succeeded.
мая 02 18:58:24 dmitriy-Inspiron-3721.lan mate-notificati[4639]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
мая 02 18:58:11 dmitriy-Inspiron-3721.lan kernel: WLC_SCAN error (-22)
мая 02 18:58:11 dmitriy-Inspiron-3721.lan kernel: ERROR @wl_cfg80211_scan : 
мая 02 18:58:11 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: wlp8s0: CTRL-EVENT-SCAN-FAILED ret=-1
мая 02 18:58:11 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: ioctl[SIOCSIWSCAN]: Invalid argument
мая 02 18:58:11 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427891.4228] device (wlp8s0): supplicant interface state: ready -> inactive
мая 02 18:58:08 dmitriy-Inspiron-3721.lan audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe=">
мая 02 18:58:08 dmitriy-Inspiron-3721.lan systemd[1]: NetworkManager-dispatcher.service: Succeeded.
мая 02 18:58:04 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427884.4723] manager: startup complete
мая 02 18:58:03 dmitriy-Inspiron-3721.lan audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-rfkill comm="systemd" exe="/usr/lib/sy>
мая 02 18:58:03 dmitriy-Inspiron-3721.lan systemd[1]: systemd-rfkill.service: Succeeded.
мая 02 18:58:01 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: wlp8s0: CTRL-EVENT-SCAN-FAILED ret=-1
мая 02 18:58:01 dmitriy-Inspiron-3721.lan kernel: WLC_SCAN error (-22)
мая 02 18:58:01 dmitriy-Inspiron-3721.lan kernel: ERROR @wl_cfg80211_scan : 
мая 02 18:58:01 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: ioctl[SIOCSIWSCAN]: Invalid argument

Инночка :*, [02.05.2020, 19:00]
мая 02 18:58:00 dmitriy-Inspiron-3721.lan ModemManager[1518]: <info>  Couldn't check support for device '/sys/devices/pci0000:00/0000:00:1c.1/0000:08:00.0': not supported by any plugin
мая 02 18:57:58 dmitriy-Inspiron-3721.lan systemd[1]: iscsi.service: Unit cannot be reloaded because it is inactive.
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.6068] manager: NetworkManager state is now CONNECTED_GLOBAL
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.6058] device (enp0s20u1): Activation: successful, device activated.
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5762] policy: set 'Проводное соединение 1' (enp0s20u1) as default for IPv4 routing and DNS
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5761] manager: NetworkManager state is now CONNECTED_SITE
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5751] manager: NetworkManager state is now CONNECTED_LOCAL
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5746] device (enp0s20u1): state change: secondaries -> activated (reason 'none', sys-iface-state: 'assume')
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5742] device (enp0s20u1): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'assume')
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5698] device (enp0s20u1): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'assume')
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5685] dhcp4 (enp0s20u1): state changed unknown -> bound
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5552] dhcp4 (enp0s20u1): activation: beginning transaction (timeout in 45 seconds)
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5546] device (enp0s20u1): state change: config -> ip-config (reason 'none', sys-iface-state: 'assume')
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5520] agent-manager: req[0x55d186445e00, :1.177/org.freedesktop.nm-applet/1001]: agent registered
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: wlp8s0: CTRL-EVENT-SCAN-FAILED ret=-1
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: ioctl[SIOCSIWSCAN]: Invalid argument
мая 02 18:57:58 dmitriy-Inspiron-3721.lan kernel: WLC_SCAN error (-22)
мая 02 18:57:58 dmitriy-Inspiron-3721.lan kernel: ERROR @wl_cfg80211_scan : 
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5415] device (wlp8s0): state change: unavailable -> disconnected (reason 'supplicant-available', sys-iface-state:>
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5413] device (wlp8s0): supplicant interface state: starting -> ready
мая 02 18:57:58 dmitriy-Inspiron-3721.lan systemd[3031]: Started dbus-:1.2-org.freedesktop.Notifications@2.service.
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5368] sup-iface[0x55d1863b1910,wlp8s0]: supports 1 scan SSIDs
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: dbus: fill_dict_with_properties dbus_interface=fi.w1.wpa_supplicant1.Interface.P2PDevice dbus_property=P2PDeviceConfig getter failed
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: ioctl[SIOCSIWENCODEEXT]: Invalid argument
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: ioctl[SIOCSIWENCODEEXT]: Invalid argument
мая 02 18:57:58 dmitriy-Inspiron-3721.lan wpa_supplicant[2861]: nl80211: deinit ifname=wlp8s0 disabled_11b_rates=0
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5056] device (enp0s20u1): state change: prepare -> config (reason 'none', sys-iface-state: 'assume')

Инночка :*, [02.05.2020, 19:00]
мая 02 18:57:58 dmitriy-Inspiron-3721.lan NetworkManager[4596]: <info>  [1588427878.5050] device (wlp8s0): supplicant interface state: init -> starting

**Comment by kuboosoft** [comment]
@dmitry-sensei 

I need check your version or source of wpa_supplicant
rpm -q wpa_supplicant

**Comment by dmitry-sensei** [comment]
Ok. ASAP

**Comment by dmitry-sensei** [comment]
rpm -q wpa_supplicant
wpa_supplicant-2.9-7.fc31.x86_64

**Comment by kuboosoft** [comment]
Very strange. Can you show me, your networking config?..

`NetworkManager --print-config`

**Comment by dmitry-sensei** [comment]
As usally asap

**Comment by dmitry-sensei** [comment]
[inna@dmitriy-Inspiron-3721 ~]$ NetworkManager --print-config
# NetworkManager configuration: /etc/NetworkManager/NetworkManager.conf

[main]
# plugins=ifcfg-rh
# rc-manager=symlink
# auth-polkit=true
# dhcp=internal

[logging]
# backend=journal
# audit=false
[inna@dmitriy-Inspiron-3721 ~]$

**Comment by kuboosoft** [comment]
@dmitry-sensei here my configuration... Do you unmarked some thing? also you can revert with the default config here...

```
[makerpm@localhost ~]$ NetworkManager --print-config
# NetworkManager configuration: /etc/NetworkManager/NetworkManager.conf (lib: 20-connectivity-fedora.conf)

[main]
# plugins=ifcfg-rh
# rc-manager=symlink
# auth-polkit=true
# dhcp=internal

[connectivity]
uri=http://fedoraproject.org/static/hotspot.txt
response=OK
interval=300

[logging]
# backend=journal
# audit=false

# no-auto-default file "/var/lib/NetworkManager/no-auto-default.state"
[makerpm@localhost ~]$ 
```

**Comment by kuboosoft** [comment]
Feel free to report the problem if it continues. Closed due to expiration.
